<?php

namespace ContainerXHx8aQe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UaDNEeAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UaDNEeA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UaDNEeA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine2' => ['services', 'doctrine', 'getDoctrineService', false],
            'passwordEncoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'doctrine2' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
