<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2leki7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2leki7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP2leki7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP2leki7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP2leki7\App_KernelDevDebugContainer([
    'container.build_hash' => 'P2leki7',
    'container.build_id' => 'f3d211f8',
    'container.build_time' => 1682408865,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2leki7');
