<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0I2zxRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0I2zxRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0I2zxRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0I2zxRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0I2zxRx\App_KernelDevDebugContainer([
    'container.build_hash' => '0I2zxRx',
    'container.build_id' => '1c1a4de5',
    'container.build_time' => 1684139520,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0I2zxRx');
