<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmGBmhU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmGBmhU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmGBmhU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmGBmhU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmGBmhU\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmGBmhU',
    'container.build_id' => 'ffaddb08',
    'container.build_time' => 1682588057,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmGBmhU');
